kpfleming/ansible-powerdns-auth

- pdns_auth_zone.py
> Remove unnecessary variable assignment

- README.md
> Provide suitable link targets for badges

- .github/workflows/build-image.yml
- .github/workflows/ci.yml
> Trigger CI job after images are built and published

- .github/workflows/build-image.yml
> Move trigger-ci to a non-matrix job so it will only fire once

- tests/playbook.yml
> Add more tests

- pdns_auth_zone.py
> Populate and update 'account' zone property

- pdns_auth_zone.py
> Begin adding support for metadata

- pdns_auth_zone.py
> Populate all metadata elements in result

- .github/workflows/ci.yml
- README.md
- tests/make_container.sh
> Changes to handle repository's new name

- pdns_auth_zone.py
This change ensures that state=present returns a populated
result structure, even for a newly-created zone.
> Refactor creation of zone result structure

- pdns_auth_zone.py
Use a class heirarchy to handle all metadata elements;
preparation for creating/updating metadata
> Refactor metadata handling

- pdns_auth_zone.py
> Remove parameter validation, let the API take care of it

- pdns_auth_zone.py
> Add wrapper classes to simplify calls to API operations

- api-swagger.json
- pdns_auth_zone.py
- tests/playbook.yml
Also incorporates fixes to the API specification sent separately
to the PowerDNS Auth repository
> Set zone metadata during zone creation

- api-swagger.json
> Import API spec with all responses declared

- .github/workflows/ci.yml
- tests/test-patk-playbook.yml
- tests/test-paz-playbook.yml
- tox.ini
Always display results of operations, and separate failure
checking from operation.
> Improve test playbooks and CI workflow

- pdns_auth_zone.py
- tests/test-paz-playbook.yml
- tox.ini
Also adds a test case for this situation.
Closes #39
> Correct behavior when 'master' list for slave zone is changed

- tests/make_tox_container.sh
> Update to current Python versions

- .github/workflows/build-image.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- pdns_auth_tsigkey.py
- pdns_auth_zone.py
> Update Actions jobs to use Ubuntu 20.04 VMs

- README.md
- pdns_auth_tsigkey.py
- pdns_auth_zone.py
- tests/make_tox_container.sh
- tests/test-patk-api-http.yml
- tests/test-patk-pdns-master.yml
- tests/test-paz-api-http.yml
- tests/test-paz-pdns-master.yml
> Add support for API docs endpoint in pdns-master (future 4.4)

- .github/workflows/build-image-and-ci-pr.yml
- .github/workflows/build-image-and-ci.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
- tests/apt-repo-pdns-auth-4.2.list
- tests/apt-repo-pdns-auth-4.4.list
- tests/make_pdns_container.sh
- tests/test-patk-pdns-4.2.yml
- tests/test-patk-pdns-4.4.yml
- tests/test-paz-pdns-4.2.yml
- tests/test-paz-pdns-4.4.yml
Also remove support for 4.2 release series
> Add support for 4.4 release series

- .github/workflows/build-image-and-ci-pr.yml
- .github/workflows/build-image-and-ci.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
- tests/make_tox_container.sh
- tox.ini
> New Python versions for testing

- tests/make_tox_container.sh
- tests/pybuild.sh
Unpack source trees outside of container
Build using a single command which runs a script
> Improve building of Python interpreters

- workflow-support/make_tox_image.sh
> Update Python 3.11 to rc1

- .ansible-lint
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- tox.ini
- workflow-support/build.yml
- workflow-support/make-galaxy-yml.yml
- workflow-support/publish.yml
- workflow-support/test-tsigkey-api-http.yml
- workflow-support/test-tsigkey-api-local.yml
- workflow-support/test-zone-api-http.yml
- workflow-support/test-zone-api-local.yml
> Add ansible-lint to linting/CI

- .github/workflows/lint.yml
- .github/workflows/publish.yml
- pyproject.toml
- src/meta/runtime.yml
- src/plugins/modules/tsigkey.py
- src/plugins/modules/zone.py
- tox.ini
Address all issues found by enabling most Ruff checks.
> Convert from flake8 to Ruff for code style and quality checking.

- .github/workflows/lint.yml
- workflow-support/make_ci_image.sh
> Improve make_ci_image script.

- src/plugins/modules/zone.py
add properties to include tsig keys for master and slave zones
> add properties to include tsig keys for master and slave zones

- .gitignore
- src/plugins/modules/zone.py
- tox.ini
- workflow-support/make_doc_site.sh
* Update docs in `zone` module to conform to current Ansible schema.
* Use antsibull-docs to validate docs during linting.
* Add script to build a docsite from module docs.
> Doc improvements

- README.md
- workflow-support/ci_paths.yml
- workflow-support/lint_paths.yml
- workflow-support/templates/galaxy.yml.j2
Switch to reference links in README.
> Add documentation links to README and Galaxy metadata.

- CHANGELOG.md
- tox.ini
- workflow-support/make_ci_image.sh
- workflow-support/versions.json
> Add support for Python 3.13.

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- pyproject.toml
- src/plugins/modules/tsigkey.py
- src/plugins/modules/zone.py
- tox.ini
- workflow-support/make_ci_image.sh
- workflow-support/versions.json
Prepare for version 24.2.0 release.
> Remove support for Python 3.8.
